import { GalleryImg } from "types";

export const GALLERY_IMAGES: Record<string, GalleryImg> = {
	"event/ark_e01" : { name: "ark_e01" , group: "ark" },
	"event/ark_e02" : { name: "ark_e02" , group: "ark" },
	"event/ark_e03" : { name: "ark_e03" , group: "ark" },
	"event/ark_e04" : { name: "ark_e04" , group: "ark" },
	"event/ark_e04b": { name: "ark_e04b", group: "ark", altOf: "event/ark_e04" },
	"event/ark_e08" : { name: "ark_e08" , group: "ark" },
	"event/ark_e09" : { name: "ark_e09" , group: "ark" },
	"event/ark_e05a": { name: "ark_e05a", group: "ark" },
	"event/ark_e05b": { name: "ark_e05b", group: "ark", altOf: "event/ark_e05a" },
	"event/ark_e06a": { name: "ark_e06a", group: "ark" },
	"event/ark_e06b": { name: "ark_e06b", group: "ark", altOf: "event/ark_e06a" },
	"event/ark_e07" : { name: "ark_e07" , group: "ark" },
	"event/ark_f01" : { name: "ark_f01" , group: "ark" },
	"event/ark_f02" : { name: "ark_f02" , group: "ark", altOf: "event/ark_f01" },
	"event/ark_f03" : { name: "ark_f03" , group: "ark" },
	"event/nero_e04": { name: "nero_e04", group: "ark" },
	"bg/cmo_06b"    : { name: "cmo_06b" , group: "ark" },
	"event/ark_e10" : { name: "ark_e10" , group: "ark" },
	"event/ark_h01" : { name: "ark_h01" , group: "ark", sensitive: true },
	"event/ark_h02" : { name: "ark_h02" , group: "ark", sensitive: true },
	"event/ark_h03" : { name: "ark_h03" , group: "ark", sensitive: true },
	"event/ark_h04" : { name: "ark_h04" , group: "ark", sensitive: true },
	"event/ark_h05" : { name: "ark_h05" , group: "ark" },
	"event/ark_h06" : { name: "ark_h06" , group: "ark", sensitive: true },
	"event/ark_h07" : { name: "ark_h07" , group: "ark", sensitive: true },
	"event/ark_h08" : { name: "ark_h08" , group: "ark", sensitive: true },
	"event/ark_h09" : { name: "ark_h09" , group: "ark", sensitive: true },
	"event/ark_h10" : { name: "ark_h10" , group: "ark", sensitive: true, unlockIds: ["event/ark_h10b"] },
	"event/ark_h10b": { name: "ark_h10b", group: "ark", sensitive: true, altOf: "event/ark_h10", source: "unused" },
	"event/ark_h11" : { name: "ark_h11" , group: "ark", sensitive: true },
	"event/ark_h12" : { name: "ark_h12" , group: "ark", sensitive: true },
	"event/ark_h13" : { name: "ark_h13" , group: "ark", sensitive: true },

	"event/cel_e01" : { name: "cel_e01" , group: "cel" },
	"event/cel_e02a": { name: "cel_e02a", group: "cel" },
	"event/cel_e02b": { name: "cel_e02b", group: "cel", altOf: "event/cel_e02a" },
	"event/cel_e03a": { name: "cel_e03a", group: "cel" },
	"event/cel_e03b": { name: "cel_e03b", group: "cel", altOf: "event/cel_e03a" },
	"event/cel_e04" : { name: "cel_e04" , group: "cel" },
	"event/cel_e05a": { name: "cel_e05a", group: "cel" },
	"event/cel_e05b": { name: "cel_e05b", group: "cel", altOf: "event/cel_e05a" },
	"event/cel_e09" : { name: "cel_e09" , group: "cel" },
	"event/cel_e06b": { name: "cel_e06b", group: "cel" },
	"event/cel_e06a": { name: "cel_e06a", group: "cel", altOf: "event/cel_e06b" },
	"event/cel_e07a": { name: "cel_e07a", group: "cel" },
	"event/cel_e07b": { name: "cel_e07b", group: "cel", altOf: "event/cel_e07a", unlockIds: ["event/cel_e07c"] },
	"event/cel_e07c": { name: "cel_e07c", group: "cel", altOf: "event/cel_e07a", source: "unused" },
	"event/cel_e08" : { name: "cel_e08" , group: "cel" },
	"event/cel_f01" : { name: "cel_f01" , group: "cel" },
	"event/cel_f01b": { name: "cel_f01b", group: "cel", altOf: "event/cel_f01" },
	"event/cel_f02" : { name: "cel_f02" , group: "cel", altOf: "event/cel_f01" },
	"bg/cmo_01"     : { name: "cmo_01"  , group: "cel", unlockIds: ["half-moon/cmo_01"] },
	"bg/cmo_02"     : { name: "cmo_02"  , group: "cel", unlockIds: ["half-moon/cmo_02"] },
	"bg/cmo_03"     : { name: "cmo_03"  , group: "cel" },
	"bg/cmo_04a"    : { name: "cmo_04a" , group: "cel" },
	"event/cel_h01" : { name: "cel_h01" , group: "cel", sensitive: true },
	"event/cel_h02" : { name: "cel_h02" , group: "cel", sensitive: true },
	"event/cel_h03a": { name: "cel_h03a", group: "cel", sensitive: true },
	"event/cel_h03b": { name: "cel_h03b", group: "cel", sensitive: true, altOf: "event/cel_h03a" },
	"event/cel_h04a": { name: "cel_h04a", group: "cel", sensitive: true },
	"event/cel_h04b": { name: "cel_h04b", group: "cel", sensitive: true, altOf: "event/cel_h04a" },
	"event/cel_h05a": { name: "cel_h05a", group: "cel", sensitive: true },
	"event/cel_h05b": { name: "cel_h05b", group: "cel", sensitive: true, altOf: "event/cel_h05a" },
	"event/cel_h06a": { name: "cel_h06a", group: "cel", sensitive: true },
	"event/cel_h06b": { name: "cel_h06b", group: "cel", sensitive: true, altOf: "event/cel_h06a" },
	"event/cel_h07a": { name: "cel_h07a", group: "cel", sensitive: true },
	"event/cel_h07b": { name: "cel_h07b", group: "cel", sensitive: true, altOf: "event/cel_h07a" },
	"event/cel_h08a": { name: "cel_h08a", group: "cel", sensitive: true },
	"event/cel_h08b": { name: "cel_h08b", group: "cel", sensitive: true, altOf: "event/cel_h08a" },
	"event/cel_h11a": { name: "cel_h11a", group: "cel", sensitive: true },
	"event/cel_h11b": { name: "cel_h11b", group: "cel", sensitive: true, altOf: "event/cel_h11a" },
	"event/cel_h09a": { name: "cel_h09a", group: "cel", sensitive: true },
	"event/cel_h09b": { name: "cel_h09b", group: "cel", sensitive: true, altOf: "event/cel_h09a" },
	"event/cel_h10" : { name: "cel_h10" , group: "cel", sensitive: true },

	"event/aki_e01" : { name: "aki_e01" , group: "aki", altOf: "event/aki_e01b" },
	"event/aki_e01b": { name: "aki_e01b", group: "aki" },
	"event/aki_e07a": { name: "aki_e07a", group: "aki" },
	"event/aki_e07b": { name: "aki_e07b", group: "aki", altOf: "event/aki_e07a" },
	"event/aki_e02" : { name: "aki_e02" , group: "aki" },
	"event/aki_e03" : { name: "aki_e03" , group: "aki" },
	"event/aki_e09" : { name: "aki_e09" , group: "aki" },
	"event/aki_e08" : { name: "aki_e08" , group: "aki" },
	"event/aki_e04b": { name: "aki_e04b", group: "aki" },
	"event/aki_e04" : { name: "aki_e04" , group: "aki", altOf: "event/aki_e04b" },
	"event/aki_e05a": { name: "aki_e05a", group: "aki" },
	"event/aki_e05b": { name: "aki_e05b", group: "aki", altOf: "event/aki_e05a" },
	"event/aki_e06" : { name: "aki_e06" , group: "aki" },
	"event/aki_f01" : { name: "aki_f01" , group: "aki" },
	"event/aki_f02" : { name: "aki_f02" , group: "aki" },
	"event/stk_e01a": { name: "stk_e01a", group: "aki" },
	"event/stk_e01b": { name: "stk_e01b", group: "aki", altOf: "event/stk_e01a" },
	"event/stk_e01c": { name: "stk_e01c", group: "aki", altOf: "event/stk_e01a" },
	"event/stk_e01d": { name: "stk_e01d", group: "aki", altOf: "event/stk_e01a" },
	"event/stk_e02" : { name: "stk_e02" , group: "aki" },
	"event/stk_e03" : { name: "stk_e03" , group: "aki" },
	"event/aki_h14" : { name: "aki_h14" , group: "aki" },
	"event/aki_h15" : { name: "aki_h15" , group: "aki", sensitive: true },
	"event/aki_h01" : { name: "aki_h01" , group: "aki" },
	"event/aki_h02" : { name: "aki_h02" , group: "aki", sensitive: true, unlockIds: ["half-moon/aki02"] },
	"event/aki_h03" : { name: "aki_h03" , group: "aki", sensitive: true },
	"event/aki_h04" : { name: "aki_h04" , group: "aki", sensitive: true },
	"event/aki_h05" : { name: "aki_h05" , group: "aki", sensitive: true },
	"event/aki_h06" : { name: "aki_h06" , group: "aki", sensitive: true },
	"event/aki_h07" : { name: "aki_h07" , group: "aki", sensitive: true },
	"event/aki_h08" : { name: "aki_h08" , group: "aki", sensitive: true },
	"event/aki_h09" : { name: "aki_h09" , group: "aki", sensitive: true },
	"event/aki_h10" : { name: "aki_h10" , group: "aki", sensitive: true },
	"event/aki_h11" : { name: "aki_h11" , group: "aki", sensitive: true },
	"event/aki_h12" : { name: "aki_h12" , group: "aki", sensitive: true },
	"event/aki_h13" : { name: "aki_h13" , group: "aki", sensitive: true },

	"event/his_e01" : { name: "his_e01" , group: "his", altOf: "event/his_e01b" },
	"event/his_e01b": { name: "his_e01b", group: "his" },
	"event/his_e02" : { name: "his_e02" , group: "his", altOf: "event/his_e02b" },
	"event/his_e02b": { name: "his_e02b", group: "his", unlockIds: ["event/his_e02b2"] },
	"event/his_e02b2":{ name: "his_e02b2", group: "his", altOf: "event/his_e02b", source: "unused" },
	"event/his_e08" : { name: "his_e08" , group: "his" },  
	"event/his_e03" : { name: "his_e03" , group: "his" },
	"event/his_e04" : { name: "his_e04" , group: "his", unlockIds: ["half-moon/his01"] },
	"event/his_e05" : { name: "his_e05" , group: "his" },
	"event/his_e09" : { name: "his_e09" , group: "his" },  
	"event/his_e06" : { name: "his_e06" , group: "his" },
	"event/his_e07a": { name: "his_e07a", group: "his" },
	"event/his_e07b": { name: "his_e07b", group: "his", altOf: "event/his_e07a" },
	"event/his_f01" : { name: "his_f01" , group: "his" },
	"event/his_f02" : { name: "his_f02" , group: "his" },
	"event/his_f03" : { name: "his_f03" , group: "his" },
	"event/hal_e01" : { name: "hal_e01" , group: "his" },
	"event/his_h16" : { name: "his_h16" , group: "his", sensitive: true },
	"event/his_h15" : { name: "his_h15" , group: "his", sensitive: true },
	"event/his_h01" : { name: "his_h01" , group: "his", sensitive: true },
	"event/his_h02" : { name: "his_h02" , group: "his", sensitive: true, altOf: "event/his_h01" },
	"event/his_h03" : { name: "his_h03" , group: "his", sensitive: true, unlockIds: ["half-moon/his02"] },
	"event/his_h04a": { name: "his_h04a", group: "his", sensitive: true },
	"event/his_h04b": { name: "his_h04b", group: "his", sensitive: true, altOf: "event/his_h04a" },
	"event/his_h12" : { name: "his_h12" , group: "his", sensitive: true },
	"event/his_h13" : { name: "his_h13" , group: "his", sensitive: true },
	"event/his_h05" : { name: "his_h05" , group: "his", sensitive: true },
	"event/his_h06" : { name: "his_h06" , group: "his", sensitive: true },
	"event/his_h06b": { name: "his_h06b", group: "his", sensitive: true, altOf: "event/his_h06" },
	"event/his_h07" : { name: "his_h07" , group: "his", sensitive: true },
	"event/his_h08" : { name: "his_h08" , group: "his", sensitive: true },
	"event/his_h09" : { name: "his_h09" , group: "his", sensitive: true },
	"event/his_h10" : { name: "his_h10" , group: "his", sensitive: true },
	"event/his_h11" : { name: "his_h11" , group: "his", sensitive: true },
	"event/his_h14" : { name: "his_h14" , group: "his", sensitive: true },

	"event/koha_e01a":{ name: "koha_e01a", group: "koha" },
	"event/koha_e01b":{ name: "koha_e01b", group: "koha", altOf: "event/koha_e01a" },
	"event/koha_e02": { name: "koha_e02", group: "koha" },
	"event/koha_e03": { name: "koha_e03", group: "koha" },
	"event/koha_e04": { name: "koha_e04", group: "koha" },
	"event/koha_e05": { name: "koha_e05", group: "koha" },
	"event/koha_e06": { name: "koha_e06", group: "koha" },
	"event/koha_e07": { name: "koha_e07", group: "koha", sensitive: true },
	"event/koha_e08": { name: "koha_e08", group: "koha" },
	"event/koha_f01": { name: "koha_f01", group: "koha" },
	"event/koha_f01b":{ name: "koha_f01b", group: "koha", altOf: "event/koha_f01" },
	"event/ao_01"   : { name: "ao_01"   , group: "koha" },
	"event/ao_02"   : { name: "ao_02"   , group: "koha" },
	"event/koha_h10": { name: "koha_h10", group: "koha", sensitive: true },
	"event/koha_h10b":{ name: "koha_h10b", group: "koha", sensitive: true, altOf: "event/koha_h10" },
	"event/koha_h11": { name: "koha_h11", group: "koha", sensitive: true },
	"event/koha_h01": { name: "koha_h01", group: "koha", sensitive: true },
	"event/koha_h02": { name: "koha_h02", group: "koha", sensitive: true },
	"event/koha_h03": { name: "koha_h03", group: "koha", sensitive: true },
	"event/koha_h04": { name: "koha_h04", group: "koha", sensitive: true },
	"event/koha_h05": { name: "koha_h05", group: "koha", sensitive: true },
	"event/koha_h06b":{ name: "koha_h06b", group: "koha", sensitive: true },
	"event/koha_h06a":{ name: "koha_h06a", group: "koha", sensitive: true, altOf: "event/koha_h06b" },
	"event/koha_h07": { name: "koha_h07", group: "koha", sensitive: true },
	"event/koha_h08": { name: "koha_h08", group: "koha", sensitive: true },

	"half-moon/aki02": { name: "aki02",  sensitive: true, altOf: "event/aki_h02", source: "half-moon" },
	"half-moon/cmo_01": { name: "cmo_01", altOf: "bg/cmo_01", source: "half-moon" },
	"half-moon/cmo_02": { name: "cmo_02", altOf: "bg/cmo_02", source: "half-moon" },
	"half-moon/his01": { name: "his01", altOf: "event/his_e04", source: "half-moon" },
	"half-moon/his02": { name: "his02", sensitive: true, altOf: "event/his_h03", source: "half-moon" },

	"bg/s01" : { name: "s01", group: "pd" },
	"bg/s02" : { name: "s02", group: "pd" },
	"bg/s03" : { name: "s03", group: "pd" },
	"bg/s04" : { name: "s04", group: "pd" },
	"bg/s05" : { name: "s05", group: "pd" },
	"bg/s06" : { name: "s06", group: "pd" },
	"bg/s07" : { name: "s07", group: "pd" },
	"bg/s08" : { name: "s08", group: "pd" },
	"bg/s09" : { name: "s09", group: "pd" },
	"bg/s10" : { name: "s10", group: "pd" },
	"bg/s11" : { name: "s11", group: "pd" },
	"bg/s12" : { name: "s12", group: "pd" },
	"bg/s13" : { name: "s13", group: "pd" },
	"bg/s14" : { name: "s14", group: "pd" },
	"bg/s15" : { name: "s15", group: "pd" },
	"bg/s16" : { name: "s16", group: "pd" },
	"bg/s17" : { name: "s17", group: "pd", sensitive: true },
	"bg/scroll19" : { name: "scroll19", group: "pd" },
	"bg/t01" : { name: "t01", group: "pd" },
	"bg/t02" : { name: "t02", group: "pd" },
	"bg/t03" : { name: "t03", group: "pd" },
	"bg/t04" : { name: "t04", group: "pd" },
	"bg/t05" : { name: "t05", group: "pd" },
	"bg/t06" : { name: "t06", group: "pd" },
	"bg/t07" : { name: "t07", group: "pd" },
}