import { GalleryImg } from "types";

export const GALLERY_IMAGES: Record<string, GalleryImg> = {
	"event/ark_e01" : { group: "ark" },
	"event/ark_e02" : { group: "ark" },
	"event/ark_e03" : { group: "ark" },
	"event/ark_e04" : { group: "ark" },
	"event/ark_e04b": { group: "ark", altOf: "event/ark_e04" },
	"event/ark_e08" : { group: "ark" },
	"event/ark_e09" : { group: "ark" },
	"event/ark_e05a": { group: "ark" },
	"event/ark_e05b": { group: "ark", altOf: "event/ark_e05a" },
	"event/ark_e06a": { group: "ark" },
	"event/ark_e06b": { group: "ark", altOf: "event/ark_e06a" },
	"event/ark_e07" : { group: "ark" },
	"event/ark_f01" : { group: "ark" },
	"event/ark_f02" : { group: "ark", altOf: "event/ark_f01" },
	"event/ark_f03" : { group: "ark" },
	"event/nero_e04": { group: "ark" },
	"bg/cmo_06b"    : { group: "ark" },
	"event/ark_e10" : { group: "ark" },
	"event/ark_h01" : { group: "ark", h: true },
	"event/ark_h02" : { group: "ark", h: true },
	"event/ark_h03" : { group: "ark", h: true },
	"event/ark_h04" : { group: "ark", h: true },
	"event/ark_h05" : { group: "ark" },
	"event/ark_h06" : { group: "ark", h: true },
	"event/ark_h07" : { group: "ark", h: true },
	"event/ark_h08" : { group: "ark", h: true },
	"event/ark_h09" : { group: "ark", h: true },
	"event/ark_h10" : { group: "ark", h: true, unlockIds: ["event/ark_h10b"] },
	"event/ark_h10b": { group: "ark", h: true, altOf: "event/ark_h10", source: "unused" },
	"event/ark_h11" : { group: "ark", h: true },
	"event/ark_h12" : { group: "ark", h: true },
	"event/ark_h13" : { group: "ark", h: true },

	"event/cel_e01" : { group: "cel" },
	"event/cel_e02a": { group: "cel" },
	"event/cel_e02b": { group: "cel", altOf: "event/cel_e02a" },
	"event/cel_e03a": { group: "cel" },
	"event/cel_e03b": { group: "cel", altOf: "event/cel_e03a" },
	"event/cel_e04" : { group: "cel" },
	"event/cel_e05a": { group: "cel" },
	"event/cel_e05b": { group: "cel", altOf: "event/cel_e05a" },
	"event/cel_e09" : { group: "cel" },
	"event/cel_e06": { group: "cel" },
	"event/cel_e07a": { group: "cel" },
	"event/cel_e07b": { group: "cel", altOf: "event/cel_e07a", unlockIds: ["event/cel_e07c"] },
	"event/cel_e07c": { group: "cel", altOf: "event/cel_e07a", source: "unused" },
	"event/cel_e08" : { group: "cel" },
	"event/cel_f01" : { group: "cel" },
	"event/cel_f01b": { group: "cel", altOf: "event/cel_f01" },
	"event/cel_f02" : { group: "cel", altOf: "event/cel_f01" },
	"bg/cmo_01"     : { group: "cel", unlockIds: ["half-moon/cmo_01"] },
	"bg/cmo_02"     : { group: "cel", unlockIds: ["half-moon/cmo_02"] },
	"bg/cmo_03"     : { group: "cel" },
	"bg/cmo_04a"    : { group: "cel" },
	"event/cel_h01" : { group: "cel", h: true },
	"event/cel_h02" : { group: "cel", h: true },
	"event/cel_h03a": { group: "cel", h: true },
	"event/cel_h03b": { group: "cel", h: true, altOf: "event/cel_h03a" },
	"event/cel_h04a": { group: "cel", h: true },
	"event/cel_h04b": { group: "cel", h: true, altOf: "event/cel_h04a" },
	"event/cel_h05a": { group: "cel", h: true },
	"event/cel_h05b": { group: "cel", h: true, altOf: "event/cel_h05a" },
	"event/cel_h06a": { group: "cel", h: true },
	"event/cel_h06b": { group: "cel", h: true, altOf: "event/cel_h06a" },
	"event/cel_h07a": { group: "cel", h: true },
	"event/cel_h07b": { group: "cel", h: true, altOf: "event/cel_h07a" },
	"event/cel_h08a": { group: "cel", h: true },
	"event/cel_h08b": { group: "cel", h: true, altOf: "event/cel_h08a" },
	"event/cel_h11a": { group: "cel", h: true },
	"event/cel_h11b": { group: "cel", h: true, altOf: "event/cel_h11a" },
	"event/cel_h09a": { group: "cel", h: true },
	"event/cel_h09b": { group: "cel", h: true, altOf: "event/cel_h09a" },
	"event/cel_h10" : { group: "cel", h: true },

	"event/aki_e01" : { group: "aki", altOf: "event/aki_e01b" },
	"event/aki_e01b": { group: "aki" },
	"event/aki_e07a": { group: "aki" },
	"event/aki_e07b": { group: "aki", altOf: "event/aki_e07a" },
	"event/aki_e02" : { group: "aki" },
	"event/aki_e03" : { group: "aki" },
	"event/aki_e09" : { group: "aki" },
	"event/aki_e08" : { group: "aki" },
	"event/aki_e04b": { group: "aki" },
	"event/aki_e04" : { group: "aki", altOf: "event/aki_e04b" },
	"event/aki_e05a": { group: "aki" },
	"event/aki_e05b": { group: "aki", altOf: "event/aki_e05a" },
	"event/aki_e06" : { group: "aki" },
	"event/aki_f01" : { group: "aki" },
	"event/aki_f02" : { group: "aki" },
	"event/stk_e01a": { group: "aki" },
	"event/stk_e01b": { group: "aki", altOf: "event/stk_e01a" },
	"event/stk_e01c": { group: "aki", altOf: "event/stk_e01a" },
	"event/stk_e01d": { group: "aki", altOf: "event/stk_e01a" },
	"event/stk_e02" : { group: "aki" },
	"event/stk_e03" : { group: "aki" },
	"event/aki_h14" : { group: "aki" },
	"event/aki_h15" : { group: "aki", h: true },
	"event/aki_h01" : { group: "aki" },
	"event/aki_h02" : { group: "aki", h: true, unlockIds: ["half-moon/aki02"] },
	"event/aki_h03" : { group: "aki", h: true },
	"event/aki_h04" : { group: "aki", h: true },
	"event/aki_h05" : { group: "aki", h: true },
	"event/aki_h06" : { group: "aki", h: true },
	"event/aki_h07" : { group: "aki", h: true },
	"event/aki_h08" : { group: "aki", h: true },
	"event/aki_h09" : { group: "aki", h: true },
	"event/aki_h10" : { group: "aki", h: true },
	"event/aki_h11" : { group: "aki", h: true },
	"event/aki_h12" : { group: "aki", h: true },
	"event/aki_h13" : { group: "aki", h: true },

	"event/his_e01" : { group: "his", altOf: "event/his_e01b" },
	"event/his_e01b": { group: "his" },
	"event/his_e02" : { group: "his", altOf: "event/his_e02b" },
	"event/his_e02b": { group: "his", unlockIds: ["event/his_e02b2"] },
	"event/his_e02b2":{ group: "his", altOf: "event/his_e02b", source: "unused" },
	"event/his_e08" : { group: "his" },  
	"event/his_e03" : { group: "his" },
	"event/his_e04" : { group: "his", unlockIds: ["half-moon/his01"] },
	"event/his_e05" : { group: "his" },
	"event/his_e09" : { group: "his" },  
	"event/his_e06" : { group: "his" },
	"event/his_e07a": { group: "his" },
	"event/his_e07b": { group: "his", altOf: "event/his_e07a" },
	"event/his_f01" : { group: "his" },
	"event/his_f02" : { group: "his" },
	"event/his_f03" : { group: "his" },
	"event/hal_e01" : { group: "his" },
	"event/his_h16" : { group: "his", h: true },
	"event/his_h15" : { group: "his", h: true },
	"event/his_h01" : { group: "his", h: true },
	"event/his_h02" : { group: "his", h: true, altOf: "event/his_h01" },
	"event/his_h03" : { group: "his", h: true, unlockIds: ["half-moon/his02"] },
	"event/his_h04a": { group: "his", h: true },
	"event/his_h04b": { group: "his", h: true, altOf: "event/his_h04a" },
	"event/his_h12" : { group: "his", h: true },
	"event/his_h13" : { group: "his", h: true },
	"event/his_h05" : { group: "his", h: true },
	"event/his_h06" : { group: "his", h: true },
	"event/his_h06b": { group: "his", h: true, altOf: "event/his_h06" },
	"event/his_h07" : { group: "his", h: true },
	"event/his_h08" : { group: "his", h: true },
	"event/his_h09" : { group: "his", h: true },
	"event/his_h10" : { group: "his", h: true },
	"event/his_h11" : { group: "his", h: true },
	"event/his_h14" : { group: "his", h: true },

	"event/koha_e01a":{ group: "koha" },
	"event/koha_e01b":{ group: "koha", altOf: "event/koha_e01a" },
	"event/koha_e02": { group: "koha" },
	"event/koha_e03": { group: "koha" },
	"event/koha_e04": { group: "koha" },
	"event/koha_e05": { group: "koha" },
	"event/koha_e06": { group: "koha" },
	"event/koha_e07": { group: "koha", h: true },
	"event/koha_e08": { group: "koha" },
	"event/koha_f01": { group: "koha" },
	"event/koha_f01b":{ group: "koha", altOf: "event/koha_f01" },
	"event/ao_01"   : { group: "koha" },
	"event/ao_02"   : { group: "koha" },
	"event/koha_h10": { group: "koha", h: true },
	"event/koha_h10b":{ group: "koha", h: true, altOf: "event/koha_h10" },
	"event/koha_h11": { group: "koha", h: true },
	"event/koha_h01": { group: "koha", h: true },
	"event/koha_h02": { group: "koha", h: true },
	"event/koha_h03": { group: "koha", h: true },
	"event/koha_h04": { group: "koha", h: true },
	"event/koha_h05": { group: "koha", h: true },
	"event/koha_h06": { group: "koha", h: true },
	"event/koha_h07": { group: "koha", h: true },
	"event/koha_h08": { group: "koha", h: true },

	"half-moon/aki02": { group: "aki", h: true, altOf: "event/aki_h02", source: "half-moon" },
	"half-moon/cmo_01": { group: "cel", altOf: "bg/cmo_01", source: "half-moon" },
	"half-moon/cmo_02": { group: "cel", altOf: "bg/cmo_02", source: "half-moon" },
	"half-moon/his01": { group: "his", altOf: "event/his_e04", source: "half-moon" },
	"half-moon/his02": { group: "his", h: true, altOf: "event/his_h03", source: "half-moon" },

	"bg/s01" : { group: "pd" },
	"bg/s02" : { group: "pd" },
	"bg/s03" : { group: "pd" },
	"bg/s04" : { group: "pd" },
	"bg/s05" : { group: "pd" },
	"bg/s06" : { group: "pd" },
	"bg/s07" : { group: "pd" },
	"bg/s08" : { group: "pd" },
	"bg/s09" : { group: "pd" },
	"bg/s10" : { group: "pd" },
	"bg/s11" : { group: "pd" },
	"bg/s12" : { group: "pd" },
	"bg/s13" : { group: "pd" },
	"bg/s14" : { group: "pd" },
	"bg/s15" : { group: "pd" },
	"bg/s16" : { group: "pd" },
	"bg/s17" : { group: "pd", h: true },
	"bg/scroll19" : { group: "pd" },
	"bg/t01" : { group: "pd" },
	"bg/t02" : { group: "pd" },
	"bg/t03" : { group: "pd" },
	"bg/t04" : { group: "pd" },
	"bg/t05" : { group: "pd" },
	"bg/t06" : { group: "pd" },
	"bg/t07" : { group: "pd" },
}