
type CharacterId = keyof typeof GALLERY_IMAGES
export type GalleryImg = {img: string, sensitive: boolean}
export const GALLERY_IMAGES = {
  ark: [
    {img: "ark_e01", sensitive: false},
    {img: "ark_e02", sensitive: false},
    {img: "ark_e03", sensitive: false},
    {img: "ark_e04", sensitive: false},
    {img: "ark_e04b", sensitive: false},
    {img: "ark_e05a", sensitive: false},
    {img: "ark_e05b", sensitive: false},
    {img: "ark_e06a", sensitive: false},
    {img: "ark_e06b", sensitive: false},
    {img: "ark_e07", sensitive: false},
    {img: "ark_e08", sensitive: false},
    {img: "ark_e09", sensitive: false},
    {img: "ark_e10", sensitive: false},
    {img: "ark_f01", sensitive: false},
    {img: "ark_f02", sensitive: false},
    {img: "ark_f03", sensitive: false},
    {img: "ark_h01", sensitive: true},
    {img: "ark_h02", sensitive: true},
    {img: "ark_h03", sensitive: true},
    {img: "ark_h04", sensitive: true},
    {img: "ark_h05", sensitive: false},
    {img: "ark_h06", sensitive: true},
    {img: "ark_h07", sensitive: true},
    {img: "ark_h08", sensitive: true},
    {img: "ark_h09", sensitive: true},
    {img: "ark_h10", sensitive: true},
    {img: "ark_h11", sensitive: true},
    {img: "ark_h12", sensitive: true},
    {img: "ark_h13", sensitive: true}
  ] as GalleryImg[],
  cel: [
    {img: "cel_e01", sensitive: false},
    {img: "cel_e02a", sensitive: false},
    {img: "cel_e02b", sensitive: false},
    {img: "cel_e03a", sensitive: false},
    {img: "cel_e03b", sensitive: false},
    {img: "cel_e04", sensitive: false},
    {img: "cel_e05a", sensitive: false},
    {img: "cel_e05b", sensitive: false},
    {img: "cel_e06a", sensitive: false},
    {img: "cel_e06b", sensitive: false},
    {img: "cel_e07a", sensitive: false},
    {img: "cel_e07b", sensitive: false},
    {img: "cel_e07c", sensitive: false},
    {img: "cel_e08", sensitive: false},
    {img: "cel_e09", sensitive: false},
    {img: "cel_f01", sensitive: false},
    {img: "cel_f01b", sensitive: false},
    {img: "cel_f02", sensitive: false},
    {img: "cel_h01", sensitive: true},
    {img: "cel_h02", sensitive: true},
    {img: "cel_h03a", sensitive: true},
    {img: "cel_h03b", sensitive: true},
    {img: "cel_h04a", sensitive: true},
    {img: "cel_h04b", sensitive: true},
    {img: "cel_h05a", sensitive: true},
    {img: "cel_h05b", sensitive: true},
    {img: "cel_h06a", sensitive: true},
    {img: "cel_h06b", sensitive: true},
    {img: "cel_h07a", sensitive: true},
    {img: "cel_h07b", sensitive: true},
    {img: "cel_h08a", sensitive: true},
    {img: "cel_h08b", sensitive: true},
    {img: "cel_h09a", sensitive: true},
    {img: "cel_h09b", sensitive: true},
    {img: "cel_h10", sensitive: true},
    {img: "cel_h11a", sensitive: true},
    {img: "cel_h11b", sensitive: true}
  ] as GalleryImg[],  
  aki: [
    {img: "aki_e01", sensitive: false},
    {img: "aki_e01b", sensitive: false},
    {img: "aki_e02", sensitive: false},
    {img: "aki_e03", sensitive: false},
    {img: "aki_e04", sensitive: false},
    {img: "aki_e04b", sensitive: false},
    {img: "aki_e05a", sensitive: false},
    {img: "aki_e05b", sensitive: false},
    {img: "aki_e06", sensitive: false},
    {img: "aki_e07a", sensitive: false},
    {img: "aki_e07b", sensitive: false},
    {img: "aki_e08", sensitive: false},
    {img: "aki_e09", sensitive: false},
    {img: "aki_f01", sensitive: false},
    {img: "aki_f02", sensitive: false},
    {img: "aki_h01", sensitive: false},
    {img: "aki_h02", sensitive: true},
    {img: "aki_h03", sensitive: true},
    {img: "aki_h04", sensitive: true},
    {img: "aki_h05", sensitive: true},
    {img: "aki_h06", sensitive: true},
    {img: "aki_h07", sensitive: true},
    {img: "aki_h08", sensitive: true},
    {img: "aki_h09", sensitive: true},
    {img: "aki_h10", sensitive: true},
    {img: "aki_h11", sensitive: true},
    {img: "aki_h12", sensitive: true},
    {img: "aki_h13", sensitive: true},
    {img: "aki_h14", sensitive: false},
    {img: "aki_h15", sensitive: true}
  ] as GalleryImg[],  
  koha: [
    {img: "koha_e01a", sensitive: false},
    {img: "koha_e01b", sensitive: false},
    {img: "koha_e02", sensitive: false},
    {img: "koha_e03", sensitive: false},
    {img: "koha_e04", sensitive: false},
    {img: "koha_e05", sensitive: false},
    {img: "koha_e06", sensitive: false},
    {img: "koha_e07", sensitive: true},
    {img: "koha_e08", sensitive: false},
    {img: "koha_f01", sensitive: false},
    {img: "koha_f01b", sensitive: false},
    {img: "koha_f02", sensitive: false},
    {img: "koha_f03", sensitive: false},
    {img: "koha_h01", sensitive: true},
    {img: "koha_h02", sensitive: true},
    {img: "koha_h03", sensitive: true},
    {img: "koha_h04", sensitive: true},
    {img: "koha_h05", sensitive: true},
    {img: "koha_h06a", sensitive: true},
    {img: "koha_h06b", sensitive: true},
    {img: "koha_h07", sensitive: true},
    {img: "koha_h08", sensitive: true},
    {img: "koha_h10", sensitive: true},
    {img: "koha_h10b", sensitive: true},
    {img: "koha_h11", sensitive: true}
  ] as GalleryImg[],  
  his: [
    {img: "his_e01", sensitive: false},
    {img: "his_e01b", sensitive: false},
    {img: "his_e02", sensitive: false},
    {img: "his_e02b", sensitive: false},
    {img: "his_e02b2", sensitive: false},
    {img: "his_e03", sensitive: false},
    {img: "his_e04", sensitive: false},
    {img: "his_e05", sensitive: false},
    {img: "his_e06", sensitive: false},
    {img: "his_e07a", sensitive: false},
    {img: "his_e07b", sensitive: false},
    {img: "his_e08", sensitive: false},
    {img: "his_e09", sensitive: false},
    {img: "his_f01", sensitive: false},
    {img: "his_f02", sensitive: false},
    {img: "his_f03", sensitive: false},
    {img: "his_h01", sensitive: true},
    {img: "his_h02", sensitive: true},
    {img: "his_h03", sensitive: true},
    {img: "his_h04a", sensitive: true},
    {img: "his_h04b", sensitive: true},
    {img: "his_h05", sensitive: true},
    {img: "his_h06", sensitive: true},
    {img: "his_h06b", sensitive: true},
    {img: "his_h07", sensitive: true},
    {img: "his_h08", sensitive: true},
    {img: "his_h09", sensitive: true},
    {img: "his_h10", sensitive: true},
    {img: "his_h11", sensitive: true},
    {img: "his_h12", sensitive: true},
    {img: "his_h13", sensitive: true},
    {img: "his_h14", sensitive: true},
    {img: "his_h15", sensitive: true},
    {img: "his_h16", sensitive: true}
  ] as GalleryImg[],  
  others: [
    {img: "ao_01", sensitive: false},
    {img: "ao_02", sensitive: false},
    {img: "hal_e01", sensitive: false},
    {img: "nero_e04", sensitive: false},
    {img: "stk_e01a", sensitive: false},
    {img: "stk_e01b", sensitive: false},
    {img: "stk_e01c", sensitive: false},
    {img: "stk_e01d", sensitive: false},
    {img: "stk_e02", sensitive: false},
    {img: "stk_e03", sensitive: false}
  ] as GalleryImg[]
}

// Function to find an image object in the GALLERY_IMAGES object based on a partial image name
export function findImageObjectByName(imageName: string): GalleryImg | undefined {
  for (const characterKey in GALLERY_IMAGES) {
    if (GALLERY_IMAGES.hasOwnProperty(characterKey)) {
      const characterImages = GALLERY_IMAGES[characterKey as keyof typeof GALLERY_IMAGES];
      const foundImage = characterImages.find((imgObj) => imageName.includes(imgObj.img))
      if (foundImage) {
        return foundImage
      }
    }
  }

  // Image not found
  return undefined
}