import { GalleryImg } from "types";

export const GALLERY_IMAGES: Record<string, GalleryImg> = {
	"ark_e01" : { name: "ark_e01" , path: "event", group: "ark" },
	"ark_e02" : { name: "ark_e02" , path: "event", group: "ark" },
	"ark_e03" : { name: "ark_e03" , path: "event", group: "ark" },
	"ark_e04" : { name: "ark_e04" , path: "event", group: "ark" },
	"ark_e04b": { name: "ark_e04b", path: "event", group: "ark", altOf: "ark_e04" },
	"ark_e08" : { name: "ark_e08" , path: "event", group: "ark" },
	"ark_e09" : { name: "ark_e09" , path: "event", group: "ark" },
	"ark_e05a": { name: "ark_e05a", path: "event", group: "ark" },
	"ark_e05b": { name: "ark_e05b", path: "event", group: "ark", altOf: "ark_e05a" },
	"ark_e06a": { name: "ark_e06a", path: "event", group: "ark" },
	"ark_e06b": { name: "ark_e06b", path: "event", group: "ark", altOf: "ark_e06a" },
	"ark_e07" : { name: "ark_e07" , path: "event", group: "ark" },
	"ark_f01" : { name: "ark_f01" , path: "event", group: "ark" },
	"ark_f02" : { name: "ark_f02" , path: "event", group: "ark", altOf: "ark_f01" },
	"ark_f03" : { name: "ark_f03" , path: "event", group: "ark" },
	"nero_e04": { name: "nero_e04", path: "event", group: "ark" },
	"cmo_06b" : { name: "cmo_06b" , path: "bg"   , group: "ark" },
	"ark_e10" : { name: "ark_e10" , path: "event", group: "ark" },
	"ark_h01" : { name: "ark_h01" , path: "event", group: "ark", sensitive: true },
	"ark_h02" : { name: "ark_h02" , path: "event", group: "ark", sensitive: true },
	"ark_h03" : { name: "ark_h03" , path: "event", group: "ark", sensitive: true },
	"ark_h04" : { name: "ark_h04" , path: "event", group: "ark", sensitive: true },
	"ark_h05" : { name: "ark_h05" , path: "event", group: "ark" },
	"ark_h06" : { name: "ark_h06" , path: "event", group: "ark", sensitive: true },
	"ark_h07" : { name: "ark_h07" , path: "event", group: "ark", sensitive: true },
	"ark_h08" : { name: "ark_h08" , path: "event", group: "ark", sensitive: true },
	"ark_h09" : { name: "ark_h09" , path: "event", group: "ark", sensitive: true },
	"ark_h10" : { name: "ark_h10" , path: "event", group: "ark", sensitive: true, unlockIds: ["ark_h10b"] },
	"ark_h10b": { name: "ark_h10b", path: "event", group: "ark", sensitive: true, altOf: "ark_h10", source: "unused" },
	"ark_h11" : { name: "ark_h11" , path: "event", group: "ark", sensitive: true },
	"ark_h12" : { name: "ark_h12" , path: "event", group: "ark", sensitive: true },
	"ark_h13" : { name: "ark_h13" , path: "event", group: "ark", sensitive: true },

	"cel_e01" : { name: "cel_e01" , path: "event", group: "cel" },
	"cel_e02a": { name: "cel_e02a", path: "event", group: "cel" },
	"cel_e02b": { name: "cel_e02b", path: "event", group: "cel", altOf: "cel_e02a" },
	"cel_e03a": { name: "cel_e03a", path: "event", group: "cel" },
	"cel_e03b": { name: "cel_e03b", path: "event", group: "cel", altOf: "cel_e03a" },
	"cel_e04" : { name: "cel_e04" , path: "event", group: "cel" },
	"cel_e05a": { name: "cel_e05a", path: "event", group: "cel" },
	"cel_e05b": { name: "cel_e05b", path: "event", group: "cel", altOf: "cel_e05a" },
	"cel_e09" : { name: "cel_e09" , path: "event", group: "cel" },
	"cel_e06b": { name: "cel_e06b", path: "event", group: "cel" },
	"cel_e06a": { name: "cel_e06a", path: "event", group: "cel", altOf: "cel_e06b" },
	"cel_e07a": { name: "cel_e07a", path: "event", group: "cel" },
	"cel_e07b": { name: "cel_e07b", path: "event", group: "cel", altOf: "cel_e07a", unlockIds: ["cel_e07c"] },
	"cel_e07c": { name: "cel_e07c", path: "event", group: "cel", altOf: "cel_e07a", source: "unused" },
	"cel_e08" : { name: "cel_e08" , path: "event", group: "cel" },
	"cel_f01" : { name: "cel_f01" , path: "event", group: "cel" },
	"cel_f01b": { name: "cel_f01b", path: "event", group: "cel", altOf: "cel_f01" },
	"cel_f02" : { name: "cel_f02" , path: "event", group: "cel", altOf: "cel_f01" },
	"cmo_01"  : { name: "cmo_01"  , path: "bg"   , group: "cel", unlockIds: ["hm_cmo_01"] },
	"cmo_02"  : { name: "cmo_02"  , path: "bg"   , group: "cel", unlockIds: ["hm_cmo_02"] },
	"cmo_03"  : { name: "cmo_03"  , path: "bg"   , group: "cel" },
	"cmo_04a" : { name: "cmo_04a" , path: "bg"   , group: "cel" },
	"cel_h01" : { name: "cel_h01" , path: "event", group: "cel", sensitive: true },
	"cel_h02" : { name: "cel_h02" , path: "event", group: "cel", sensitive: true },
	"cel_h03a": { name: "cel_h03a", path: "event", group: "cel", sensitive: true },
	"cel_h03b": { name: "cel_h03b", path: "event", group: "cel", sensitive: true, altOf: "cel_h03a" },
	"cel_h04a": { name: "cel_h04a", path: "event", group: "cel", sensitive: true },
	"cel_h04b": { name: "cel_h04b", path: "event", group: "cel", sensitive: true, altOf: "cel_h04a" },
	"cel_h05a": { name: "cel_h05a", path: "event", group: "cel", sensitive: true },
	"cel_h05b": { name: "cel_h05b", path: "event", group: "cel", sensitive: true, altOf: "cel_h05a" },
	"cel_h06a": { name: "cel_h06a", path: "event", group: "cel", sensitive: true },
	"cel_h06b": { name: "cel_h06b", path: "event", group: "cel", sensitive: true, altOf: "cel_h06a" },
	"cel_h07a": { name: "cel_h07a", path: "event", group: "cel", sensitive: true },
	"cel_h07b": { name: "cel_h07b", path: "event", group: "cel", sensitive: true, altOf: "cel_h07a" },
	"cel_h08a": { name: "cel_h08a", path: "event", group: "cel", sensitive: true },
	"cel_h08b": { name: "cel_h08b", path: "event", group: "cel", sensitive: true, altOf: "cel_h08a" },
	"cel_h11a": { name: "cel_h11a", path: "event", group: "cel", sensitive: true },
	"cel_h11b": { name: "cel_h11b", path: "event", group: "cel", sensitive: true, altOf: "cel_h11a" },
	"cel_h09a": { name: "cel_h09a", path: "event", group: "cel", sensitive: true },
	"cel_h09b": { name: "cel_h09b", path: "event", group: "cel", sensitive: true, altOf: "cel_h09a" },
	"cel_h10" : { name: "cel_h10" , path: "event", group: "cel", sensitive: true },

	"aki_e01" : { name: "aki_e01" , path: "event", group: "aki", altOf: "aki_e01b" },
	"aki_e01b": { name: "aki_e01b", path: "event", group: "aki" },
	"aki_e07a": { name: "aki_e07a", path: "event", group: "aki" },
	"aki_e07b": { name: "aki_e07b", path: "event", group: "aki", altOf: "aki_e07a" },
	"aki_e02" : { name: "aki_e02" , path: "event", group: "aki" },
	"aki_e03" : { name: "aki_e03" , path: "event", group: "aki" },
	"aki_e09" : { name: "aki_e09" , path: "event", group: "aki" },
	"aki_e08" : { name: "aki_e08" , path: "event", group: "aki" },
	"aki_e04b": { name: "aki_e04b", path: "event", group: "aki" },
	"aki_e04" : { name: "aki_e04" , path: "event", group: "aki", altOf: "aki_e04b" },
	"aki_e05a": { name: "aki_e05a", path: "event", group: "aki" },
	"aki_e05b": { name: "aki_e05b", path: "event", group: "aki", altOf: "aki_e05a" },
	"aki_e06" : { name: "aki_e06" , path: "event", group: "aki" },
	"aki_f01" : { name: "aki_f01" , path: "event", group: "aki" },
	"aki_f02" : { name: "aki_f02" , path: "event", group: "aki" },
	"stk_e01a": { name: "stk_e01a", path: "event", group: "aki" },
	"stk_e01b": { name: "stk_e01b", path: "event", group: "aki", altOf: "stk_e01a" },
	"stk_e01c": { name: "stk_e01c", path: "event", group: "aki", altOf: "stk_e01a" },
	"stk_e01d": { name: "stk_e01d", path: "event", group: "aki", altOf: "stk_e01a" },
	"stk_e02" : { name: "stk_e02" , path: "event", group: "aki" },
	"stk_e03" : { name: "stk_e03" , path: "event", group: "aki" },
	"aki_h14" : { name: "aki_h14" , path: "event", group: "aki" },
	"aki_h15" : { name: "aki_h15" , path: "event", group: "aki", sensitive: true },
	"aki_h01" : { name: "aki_h01" , path: "event", group: "aki" },
	"aki_h02" : { name: "aki_h02" , path: "event", group: "aki", sensitive: true, unlockIds: ["hm_aki02"] },
	"aki_h03" : { name: "aki_h03" , path: "event", group: "aki", sensitive: true },
	"aki_h04" : { name: "aki_h04" , path: "event", group: "aki", sensitive: true },
	"aki_h05" : { name: "aki_h05" , path: "event", group: "aki", sensitive: true },
	"aki_h06" : { name: "aki_h06" , path: "event", group: "aki", sensitive: true },
	"aki_h07" : { name: "aki_h07" , path: "event", group: "aki", sensitive: true },
	"aki_h08" : { name: "aki_h08" , path: "event", group: "aki", sensitive: true },
	"aki_h09" : { name: "aki_h09" , path: "event", group: "aki", sensitive: true },
	"aki_h10" : { name: "aki_h10" , path: "event", group: "aki", sensitive: true },
	"aki_h11" : { name: "aki_h11" , path: "event", group: "aki", sensitive: true },
	"aki_h12" : { name: "aki_h12" , path: "event", group: "aki", sensitive: true },
	"aki_h13" : { name: "aki_h13" , path: "event", group: "aki", sensitive: true },

	"his_e01" : { name: "his_e01" , path: "event", group: "his", altOf: "his_e01b" },
	"his_e01b": { name: "his_e01b", path: "event", group: "his" },
	"his_e02" : { name: "his_e02" , path: "event", group: "his", altOf: "his_e02b" },
	"his_e02b": { name: "his_e02b", path: "event", group: "his", unlockIds: ["his_e02b2"] },
	"his_e02b2":{ name: "his_e02b2",path: "event", group: "his", altOf: "his_e02b", source: "unused" },
	"his_e08" : { name: "his_e08" , path: "event", group: "his" },  
	"his_e03" : { name: "his_e03" , path: "event", group: "his" },
	"his_e04" : { name: "his_e04" , path: "event", group: "his", unlockIds: ["hm_his01"] },
	"his_e05" : { name: "his_e05" , path: "event", group: "his" },
	"his_e09" : { name: "his_e09" , path: "event", group: "his" },  
	"his_e06" : { name: "his_e06" , path: "event", group: "his" },
	"his_e07a": { name: "his_e07a", path: "event", group: "his" },
	"his_e07b": { name: "his_e07b", path: "event", group: "his", altOf: "his_e07a" },
	"his_f01" : { name: "his_f01" , path: "event", group: "his" },
	"his_f02" : { name: "his_f02" , path: "event", group: "his" },
	"his_f03" : { name: "his_f03" , path: "event", group: "his" },
	"hal_e01" : { name: "hal_e01" , path: "event", group: "his" },
	"his_h16" : { name: "his_h16" , path: "event", group: "his", sensitive: true },
	"his_h15" : { name: "his_h15" , path: "event", group: "his", sensitive: true },
	"his_h01" : { name: "his_h01" , path: "event", group: "his", sensitive: true, altOf: "his_h02" },
	"his_h02" : { name: "his_h02" , path: "event", group: "his", sensitive: true },
	"his_h03" : { name: "his_h03" , path: "event", group: "his", sensitive: true, unlockIds: ["hm_his02"] },
	"his_h04a": { name: "his_h04a", path: "event", group: "his", sensitive: true },
	"his_h04b": { name: "his_h04b", path: "event", group: "his", sensitive: true, altOf: "his_h04a" },
	"his_h12" : { name: "his_h12" , path: "event", group: "his", sensitive: true },
	"his_h13" : { name: "his_h13" , path: "event", group: "his", sensitive: true },
	"his_h05" : { name: "his_h05" , path: "event", group: "his", sensitive: true },
	"his_h06" : { name: "his_h06" , path: "event", group: "his", sensitive: true },
	"his_h06b": { name: "his_h06b", path: "event", group: "his", sensitive: true, altOf: "his_h06" },
	"his_h07" : { name: "his_h07" , path: "event", group: "his", sensitive: true },
	"his_h08" : { name: "his_h08" , path: "event", group: "his", sensitive: true },
	"his_h09" : { name: "his_h09" , path: "event", group: "his", sensitive: true },
	"his_h10" : { name: "his_h10" , path: "event", group: "his", sensitive: true },
	"his_h11" : { name: "his_h11" , path: "event", group: "his", sensitive: true },
	"his_h14" : { name: "his_h14" , path: "event", group: "his", sensitive: true },

	"koha_e01a":{ name: "koha_e01a",path: "event", group: "koha" },
	"koha_e01b":{ name: "koha_e01b",path: "event", group: "koha", altOf: "koha_e01a" },
	"koha_e02": { name: "koha_e02", path: "event", group: "koha" },
	"koha_e03": { name: "koha_e03", path: "event", group: "koha" },
	"koha_e04": { name: "koha_e04", path: "event", group: "koha" },
	"koha_e05": { name: "koha_e05", path: "event", group: "koha" },
	"koha_e06": { name: "koha_e06", path: "event", group: "koha" },
	"koha_e07": { name: "koha_e07", path: "event", group: "koha", sensitive: true },
	"koha_e08": { name: "koha_e08", path: "event", group: "koha" },
	"koha_f01": { name: "koha_f01", path: "event", group: "koha" },
	"koha_f01b":{ name: "koha_f01b",path: "event", group: "koha", altOf: "koha_f01" },
	"ao_01"   : { name: "ao_01"   , path: "event", group: "koha" },
	"ao_02"   : { name: "ao_02"   , path: "event", group: "koha" },
	"koha_h10": { name: "koha_h10", path: "event", group: "koha", sensitive: true },
	"koha_h10b":{ name: "koha_h10b",path: "event", group: "koha", sensitive: true, altOf: "koha_h10" },
	"koha_h11": { name: "koha_h11", path: "event", group: "koha", sensitive: true },
	"koha_h01": { name: "koha_h01", path: "event", group: "koha", sensitive: true },
	"koha_h02": { name: "koha_h02", path: "event", group: "koha", sensitive: true },
	"koha_h03": { name: "koha_h03", path: "event", group: "koha", sensitive: true },
	"koha_h04": { name: "koha_h04", path: "event", group: "koha", sensitive: true },
	"koha_h05": { name: "koha_h05", path: "event", group: "koha", sensitive: true },
	"koha_h06b":{ name: "koha_h06b",path: "event", group: "koha", sensitive: true },
	"koha_h06a":{ name: "koha_h06a",path: "event", group: "koha", sensitive: true, altOf: "koha_h06b" },
	"koha_h07": { name: "koha_h07", path: "event", group: "koha", sensitive: true },
	"koha_h08": { name: "koha_h08", path: "event", group: "koha", sensitive: true },

	"hm_aki02": { name: "hm_aki02", path: "half-moon", sensitive: true, altOf: "aki_h02", source: "half-moon" },
	"hm_cmo_01": { name: "hm_cmo_01", path: "half-moon", altOf: "cmo_01", source: "half-moon" },
	"hm_cmo_02": { name: "hm_cmo_02", path: "half-moon", altOf: "cmo_02", source: "half-moon" },
	"hm_his01": { name: "hm_his01", path: "half-moon", altOf: "his_e04", source: "half-moon" },
	"hm_his02": { name: "hm_his02", path: "half-moon", sensitive: true, altOf: "his_h03", source: "half-moon" },
}

export const GALLERY_IMAGES_PD: Record<string, GalleryImg> = {
	"s01" : { name: "s01" , path: "bg" },
	"s02" : { name: "s02" , path: "bg" },
	"s03" : { name: "s03" , path: "bg" },
	"s04" : { name: "s04" , path: "bg" },
	"s05" : { name: "s05" , path: "bg" },
	"s06" : { name: "s06" , path: "bg" },
	"s07" : { name: "s07" , path: "bg" },
	"s08" : { name: "s08" , path: "bg" },
	"s09" : { name: "s09" , path: "bg" },
	"s10" : { name: "s10" , path: "bg" },
	"s11" : { name: "s11" , path: "bg" },
	"s12" : { name: "s12" , path: "bg" },
	"s13" : { name: "s13" , path: "bg" },
	"s14" : { name: "s14" , path: "bg" },
	"s15" : { name: "s15" , path: "bg" },
	"s16" : { name: "s16" , path: "bg" },
	"s17" : { name: "s17" , path: "bg" , sensitive: true },
	"scroll19" : { name: "scroll19" , path: "bg" },
	"t01" : { name: "t01" , path: "bg" },
	"t02" : { name: "t02" , path: "bg" },
	"t03" : { name: "t03" , path: "bg" },
	"t04" : { name: "t04" , path: "bg" },
	"t05" : { name: "t05" , path: "bg" },
	"t06" : { name: "t06" , path: "bg" },
	"t07" : { name: "t07" , path: "bg" },
}